vim.keymap.set("n", "<leader>Y", [["+Y]], { desc = "Copy line to clipboard" })
vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("x", "<leader>h", [[:sort<CR>]], { desc = "Sort lines" })
vim.keymap.set("x", "<leader>p", [["_dP]], { desc = "Paste without overwriting register" })
vim.keymap.set({ "n", "v" }, "<leader>d", [["_d]], { desc = "Delete to black hole register" })
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]], { desc = "Copy to clipboard" })
vim.keymap.set({ "n", "v" }, "&", "g_")
vim.keymap.set({ "n", "v" }, "£", "0")
vim.keymap.set({ "n", "v" }, "<leader>/", "/\\c", { desc = "Forwards search case insensitive" })
vim.keymap.set({ "n", "v" }, "<leader>?", "?\\c", { desc = "Backwards search case insensitive" })
vim.keymap.set({ "n", "v" }, "<leader>#", [[:b#<CR>]], { silent = true, desc = "Switch to alternate buffer" })
vim.keymap.set("n", "<leader>jcf", function()
	local path = vim.fn.expand("%")
	vim.fn.setreg('"', path)
	print("Copied " .. path .. ' to register "')
end, { desc = "Copy current buffer path to anonymous register" })
vim.keymap.set("x", "<leader>jsi", [[:s/^\s*\zs\ze\S/]], { desc = "Prepend to lines" })
vim.keymap.set("x", "<leader>jsa", [[:s/\S\zs$/]], { desc = "Append to lines" })
vim.keymap.set("n", "<leader>ot", [[:!wt.exe -d "%:p:h"<CR>]], { desc = "Open wt at this file's directory" })
vim.keymap.set("n", "<leader>oe", [[:!explorer.exe "%:p:h"<CR>]], { desc = "Open explorer at this file's directory" })
vim.keymap.set("n", "<leader>opt", [[:!wt.exe -d .<CR>]], { desc = "Open wt at cwd" })
vim.keymap.set("n", "<leader>ope", [[:!explorer.exe .<CR>]], { desc = "Open explorer at cwd" })
vim.keymap.set("n", "<leader>w", vim.cmd.w, { desc = "Save current buffer" })
vim.keymap.set("n", "<leader><C-q>", [[:tabclose<CR>]], { silent = true, desc = "Close current tab" })
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "-", "<C-w><")
vim.keymap.set("n", "+", "<C-w>>")
vim.keymap.set("n", "<M-->", "<C-w>-")
vim.keymap.set("n", "<M-+>", "<C-w>+")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("t", "<C-Space>", "<C-\\><C-n>")
vim.keymap.set("t", "<C-h>", "<C-\\><C-n><C-w>h")
vim.keymap.set("t", "<C-j>", "<C-\\><C-n><C-w>j")
vim.keymap.set("t", "<C-k>", "<C-\\><C-n><C-w>k")
vim.keymap.set("t", "<C-l>", "<C-\\><C-n><C-w>l")
vim.keymap.set(
	"n",
	"<leader>jss",
	[[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]],
	{ desc = "Replace word under cursor" }
)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<C-w>t", [[:tabe %<CR>]], { silent = true, desc = "Open current buffer in a new tab" })
vim.keymap.set("n", "<leader>c", "<C-w>c", { desc = "Close window" })

vim.api.nvim_create_user_command("Redir", [[:redir @" | silent <args> | redir END | enew | put"]], { nargs = 1 })

if vim.g.neovide then
	vim.keymap.set({ "n", "v" }, "<C-c>", '"+y', { desc = "Copy to clipboard" })
	-- vim.keymap.set({ "n", "v" }, "<C-x>", '"+x', { desc = "Cut to clipboard" })
	vim.keymap.set({ "n", "v" }, "<C-v>", '"+gP', { desc = "Paste from clipboard" })
	vim.keymap.set({ "i", "t" }, "<C-v>", '<esc>"+gp', { desc = "Paste from clipboard" })
end
